name: module3_task1
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  module3_task0:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: lint
        run: |
          cd module3_task1/
          make lint
      - name: Setup tools
        run: |
          cd module3_task1/
          ./setup.sh
      - name: build
        run: |
          cd module3_task1/
          make build
      - name: validate
        run: |
          cd module3_task1/
          make validate        
      - name: integration tests
        run: |
          cd module3_task1/
          make integration-tests
      - name: unit-tests
        run: |
          cd module3_task1/
          make unit-tests
